server:
    port: 8090
    # 配置数据源--连接池druid，参数可以省略
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/ssm_shopping?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
      url: jdbc:mysql://192.168.1.104:3306/e_shopping?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
      username: root
      password: 123456
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#
#    poolPreparedStatements: false
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.eshopping.pojo
    # SpringBoot中多数据源 配置mybatis 驼峰命名不管用，带下划线字段返回null值
    configuration:
        map-underscore-to-camel-case: true